server:
  port: 6080 # 注册中心占用8080端口

spring.redis.host: 59.110.235.199
spring.redis.port: 6379
#spring.redis.password=
spring.redis.database: 1
spring.redis.pool.max-active: 8
spring.redis.pool.max-wait: -1
spring.redis.pool.max-idle: 500
spring.redis.pool.min-idle: 0
spring.redis.timeout: 0

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #其实就是 http://localhost:6080/eureka/