spring:
  application:
    name: userService
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6080/eureka/  #注册中心地址
  instance:
    hostname: localhost
    instance-id: http://localhost:6083
server:
  port: 6083