server:
  port: 6081
spring:
  application:
    name: config-Center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Mikesame/ClaySystem.git
          searchPaths: '{application}'  #搜索各个以服务名命名的文件夹下的所有yml
eureka:
  instance:
    hostname: localhost
    instance-id: localhost:6081
  client:
    serviceUrl:
      defaultZone: http://localhost:6080/eureka/  #注册中心地址